source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.0"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.4", ">= 7.0.4.1"

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem "sprockets-rails"

# Use mysql as the database for Active Record
gem "mysql2", "~> 0.5"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.0"

# Bundle and transpile JavaScript [https://github.com/rails/jsbundling-rails]
gem "jsbundling-rails"

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails"

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "stimulus-rails"

# Bundle and process CSS [https://github.com/rails/cssbundling-rails]
gem "cssbundling-rails"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"

# Use Redis adapter to run Action Cable in production
gem "redis", "~> 4.0"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Use Sass to process CSS
# gem "sassc-rails"

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

# sentry
gem "sentry-ruby"
gem "sentry-rails"

# job schedulers
gem 'sidekiq'
gem 'sidekiq-failures'
gem 'redis-namespace'
# END job schedulers

# HTTP client
gem 'faraday'
gem 'faraday_middleware'
# END HTTP client

# shrine
gem 'shrine', '~> 3.0'
gem 'aws-sdk-s3', '~> 1.14' # for AWS S3 storage
gem 'mime-types', require: 'mime/types/full'
gem 'image_processing'
gem 'mini_magick'
# END shrine

# ActiveRecord Expansion
gem 'sorcery'
gem 'enum_help'
gem 'ancestry'
gem 'activerecord-import'
gem 'discard', '~> 1.2'
gem 'deep_cloneable'

# i18n
gem 'rails-i18n'

# crontab
gem 'whenever', require: false

# error page
# gem 'rambulance'

# Bot measures
gem 'recaptcha'

# pagenation
gem 'kaminari'
gem 'bootstrap4-kaminari-views'

# sitemap generator
gem 'sitemap_generator', github: 'akkijp/sitemap_generator', ref: 'cc702f1df364e3590f7e90d1bb3988c24e8e37b7'

# payment
gem 'stripe'

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
  gem 'pry-rails'
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"

  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler"

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara"
  gem "selenium-webdriver"
  gem "webdrivers"
  gem 'rspec-rails', '~> 6.0.0'
  gem "factory_bot_rails"
end
